// VENDOR TYPES
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ADD_TO_ORDERS = "ADD_TO_ORDERS";
export const DELETE_ORDERS = "DELETE_ORDERS";
export const UPDATE_ORDERS = "UPDATE_ORDERS";
export const UPDATE_VENDOR_PROFILE = "UPDATE_PROFILE";
export const SUPPORT_RESPONSE = "SUPPORT_RESPONSE";

// USER TYPES
export const ORDER_AGAIN = "ORDER_AGAIN";
export const ADD_TO_CART = "ADD_TO_CART";
export const SUPPORT_REQUEST = "SUPPORT_REQUEST";
export const ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const ADD_NEW_METHOD = "ADD_NEW_METHOD";
export const UPDATE_METHOD = "UPDATE_METHOD";
export const DELETE_METHOD = "DELETE_METHOD";
export const CANCEL_ORDER = "CANCEL_ORDER";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
