// VENDOR TYPES
const ADD_PRODUCT = "ADD_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const ADD_TO_ORDERS = "ADD_TO_ORDERS";
const DELETE_ORDERS = "DELETE_ORDERS";
const UPDATE_ORDERS = "UPDATE_ORDERS";
const UPDATE_PROFILE = "UPDATE_PROFILE";
const SUPPORT_RESPONSE = "SUPPORT_RESPONSE";

// USER TYPES
const ORDER_AGAIN = "ORDER_AGAIN";
const ADD_TO_CART = "ADD_TO_CART";
const SUPPORT_REQUEST = "SUPPORT_REQUEST";
const ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS";
const ADD_NEW_METHOD = "ADD_NEW_METHOD";
const CANCEL_ORDER = "CANCEL_ORDER";
