// VENDOR TYPES
export const ADD_VENDOR = "ADD_VENDOR";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_TO_VENDOR = "ADD_PRODUCT_TO_VENDOR";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_FV = "DELETE_PRODUCT_FV";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ADD_TO_ORDERS = "ADD_TO_ORDERS";
export const DELETE_ORDERS = "DELETE_ORDERS";
export const UPDATE_ORDERS = "UPDATE_ORDERS";
export const UPDATE_VENDOR_PROFILE = "UPDATE_PROFILE";
export const SUPPORT_RESPONSE = "SUPPORT_RESPONSE";
export const ADD_TO_BALANCE = "ADD_TO_BALANCE";
export const REMOVE_FROM_BALANCE = "REMOVE_FROM_BALANCE";
export const ADD_TO_DAILY_BALANCE = "ADD_TO_DAILY_BALANCE";
export const REMOVE_FROM_DAILY_BALANCE = "REMOVE_FROM_DAILY_BALANCE";

// USER TYPES
export const ADD_USER = "ADD_USER";
export const ORDER_AGAIN = "ORDER_AGAIN";
export const ADD_TO_CART = "ADD_TO_CART";
export const SUPPORT_REQUEST = "SUPPORT_REQUEST";
export const ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const ADD_NEW_METHOD = "ADD_NEW_METHOD";
export const UPDATE_METHOD = "UPDATE_METHOD";
export const DELETE_METHOD = "DELETE_METHOD";
export const CANCEL_ORDER = "CANCEL_ORDER";
export const ADD_PRODUCT_K = "ADD_PRODUCT_K";
export const EDITE_PRODUCT_K = "EDITE_PRODUCT_K";
export const DELETE_PRODUCT_K = "DELETE_PRODUCT_K";
export const CHANGE_CART = "CHANGE_CART";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
